spring:
  application:
    name: spring-security
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mwashmyner
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

